confirm-before-quit = false

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[cursor]
blinking = true

[fonts]
family = "0xProto Nerd Font"

[window]
macos-use-unified-titlebar = true

[navigation]
mode = "NativeTab"
