blocks:
  - date
  - size
  - name
color:
  when: auto
  theme: term_color
date: '+%Y-%m-%d %H:%M:%S'
display: almost-all
indicators: true
sorting:
  column: version
  dir-grouping: none
hyperlink: auto
