#!/usr/bin/env fish

set --global current_dir (realpath (dirname (status filename)))

pushd $current_dir
for script in **/eupdate.fish
    echo '###' $script
    eval $script
end
popd

echo '### Done'
date
