# update homebrew
update
upgrade

# install package
install zsh
install zsh-completions
install coreutils
install lv
install autojump
install rmtrash
install ack
install colordiff
install rpl
install w3m
install nkf
install lha
install p7zip
install git
install git-flow
install hub
install tig
install repo
install stgit
install jq
install ascii
install libimobiledevice
install imagemagick
install graphicsmagick
install ncftp
install minicom
install haskell-platform

# install homebrew-cask
tap phinze/cask
install brew-cask

# cask install : QuickLook Text
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install quicklook-json
cask install qlprettypatch

# cask install : QuickLook Archive
cask install betterzipql
cask install suspicious-package

# cask install : QuickLook Binary
cask install provisioning
cask install ipaql
cask install quicklook-csv

