source 'https://rubygems.org'

# dotfiles
gem 'homesick'

# cocoa
gem 'cocoapods'
gem 'synx'
gem 'xcpretty'

# ruby
gem 'pry'

# atom-beautify
gem 'ruby-beautify'
gem 'htmlbeautifier'

# asciidoctor
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'pygments.rb'

