source 'https://rubygems.org'

# dotfiles
gem 'homesick'

# cocoa
gem 'cocoapods'
gem 'synx'
gem 'xcpretty'
gem 'xcjobs'
gem 'nomad-cli'

# ruby
gem 'pry'

# atom-beautify
gem 'ruby-beautify'
gem 'htmlbeautifier'

# markdown
gem 'redcarpet'

# asciidoctor
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'pygments.rb'

