# update homebrew
update
upgrade

# install homebrew-cask
tap phinze/cask
install brew-cask

# cask install : QuickLook Text
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install quicklook-json
cask install qlprettypatch

# cask install : QuickLook Archive
cask install betterzipql
cask install suspicious-package

# cask install : QuickLook Binary
cask install provisioning
cask install ipaql
cask install quicklook-csv

