# Homebrew 更新
update

# Formula 更新
upgrade

# homebrew-cask インストール
tap phinze/cask
install brew-cask

# QuickLook : テキスト
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install quicklook-json
cask install qlprettypatch

# QuickLook : アーカイブ
cask install betterzipql
cask install suspicious-package

# QuickLook : バイナリ
cask install provisioning
cask install ipaql
cask install quicklook-csv

