import = ["~/.config/alacritty/themes/themes/ayu_light.toml"]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
startup_mode = "Maximized"
dynamic_padding = true

[window.padding]
x = 4
y = 4

[font]
size = 14
normal.family = "0xProto Nerd Font"

[cursor.style]
shape = "Beam"
blinking = "On"
