import = ["~/.config/alacritty/themes/themes/ayu_light.toml"]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[font]
size = 13
normal.family = "0xProto Nerd Font"

[window.padding]
x = 4
y = 4

[cursor.style]
shape = "Beam"
blinking = "On"
